apiVersion: v1
kind: Pod
metadata:
  name: cnfs-write-pod
spec:
  # TODO: set this to actual Kata RuntimeClass name if needed
  runtimeClassName: kata-qemu
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "hello-from-cnfs" > /data/test.txt;
          sync;
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cnfs-kata-nfs-pvc
