apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.cnfs.interposer.io
spec:
  attachRequired: false
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
