apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnfs-kata-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cnfs-kata-nfs
