# kata-pv-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: kata-host-storage
