apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  runtimeClassName: kata-qemu
  containers:
  - image: ubuntu
    name: ubuntu
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN", "NET_ADMIN"]
    command: ["sleep", "604800"]
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/bash
            - -c
            - |
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get install -y \
                nfs-common \
                iproute2 \
                iputils-ping
